const response = {
  status: 200,
  statusText: "OK",
  headers: {
    "x-powered-by": "Express",
    "access-control-allow-origin": "*",
    "access-control-allow-headers": "Origin, X-Requested-With, Content-Type, Accept, Authorization",
    "content-type": "application/json; charset=utf-8",
    "content-length": "6926",
    etag: 'W/"1b0e-49LKM4g9esvUargW3DERHsNgOu8"',
    date: "Thu, 01 Sep 2022 08:18:51 GMT",
    connection: "close",
  },
  config: {},
  data: {
    permission: true,
    user: {
      id: 32,
      firstName: "test",
      lastName: "test",
      email: "test@test.com",
      username: "test",
      uccxUsername: "test",
      // password: '$2a$12$fXcAAVTAwfTHDPsC7d8N.uvw9/SEd1iYzC/4yQS3whEQ2iH/pCSOa',
      password: "123456",
      accessFailedCount: 0,
      lockedOutEndDate: null,
      createdAt: "2020-03-01T11:30:32.286Z",
      updatedAt: "2022-07-26T10:18:52.057Z",
      Tenant: "test",
      Team: null,
      roleId: 1,
      // dbRole: [Object],
      //permissions: [Array]
      dbRole: {
        id: 1,
        role: "מנהל מערכת",
        Tenant: "test",
        createdAt: "2020-02-03T08:37:54.634Z",
        updatedAt: "2020-02-03T08:37:54.634Z",
        permissions: [],
      },
      permissions: [
        "ניהול משתמשים",
        "ניהול תפקידים",
        "ניהול שעות פעילות",
        "ניהול מספרי VIP",
        "ניהול קבצי שמע",
        "ניהול הקלטות לאפליקציה",
        "ניהול שעות פעילות לאפליקציה",
        "ניהול הקלטות לצמתים",
        "ניהול הכרזות",
        "סרגל נציג",
        "ניהול קמפיין",
        "ניהול קונפיגורציה",
        "ניהול נציגים למיומנות",
        "ניהול דוחות היסטוריים",
        "ניהול זמן אמת",
        "ניהול מיומנויות לנציג",
        "ניהול קבוצות",
        "ניהול לקוחות",
        "גישה לקומבוקס",
        "גישה לפינס",
        "צפייה בדוחות היסטוריים",
        "הוספת קישורים לדוחות היסטוריים",
      ],
    },
  },
};

export default response;
